//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace projectmain1._1.Pages.Admin {
    
    
    public partial class MilasBarbersAdmin {
        
        /// <summary>
        /// AdminVerify control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::projectmain1._1.Pages.Admin.Controls.AdminVerify AdminVerify;
    }
}
